/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import srt.freelancers.Projeto;
import srt.freelancers.Repositorio;
import srt.freelancers.Tarefas;
import srt.freelancers.Utilizador;

/**
 *
 * @author pedro
 */
public class GerirProjetos extends javax.swing.JPanel {

    public BigDecimal userid;
    private PaginaInicial parentFrame;
    private JPanel painelVisivel;
    private Utilizador utilizador;

    /**
     * Creates new form GerirProjetos
     */
    public GerirProjetos(PaginaInicial parent, String user) {
        initComponents();
        parentFrame = parent;
        Utilizador ut = new Utilizador();
        utilizador = ut.setUser(user);

        DefaultTableModel res1 = (DefaultTableModel) this.tableProjetos.getModel();
        DefaultTableModel res2 = (DefaultTableModel) this.tableTarefas.getModel();
        
        //Imprime a tabela Projetos
        for (Projeto p : Repositorio.getInstance().getProjeto_tarefas().keySet()) {
            if (p.getUtil().contains(utilizador)) {
                Object[] dados = {p.getNome(), p.getPrecoPhora(), p.getTotalHoras(), p.getNomeCliente()};
                res1.addRow(dados);
            }
        }
        //Imprime a Tabela Tarefas
        for (Tarefas t : Repositorio.getInstance().getTarefas()) {
            res2.addRow(new Object[]{t.getDescricao()});
        }

    }
    
    /**
     * Atualiza a tabela
     */
    public void RefreshTable(){
                DefaultTableModel model = (DefaultTableModel)tableProjetos.getModel();
                model.setRowCount(0);
                for (Projeto p : Repositorio.getInstance().getProjeto_tarefas().keySet()) {
                    if (p.getUtil().contains(utilizador)) {
                        Object[] dados = {p.getNome(), p.getPrecoPhora(), p.getTotalHoras(), p.getNomeCliente()};
                        model.addRow(dados);
                    }
        
        }
    }
    
    /**
     * Verifica se existe na Tabela
     * @param Tarefa tarefa
     * return boolean verifica_desp 
     */
    public boolean verificaTarefa(Tarefas tarefa) {
        boolean verifica_desp = false;

        for (Tarefas t : Repositorio.getInstance().getTarefas()) {
            if (tarefa.getDescricao().equals(t.getDescricao())) {
                verifica_desp = true;
            }
        }

        return verifica_desp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTarefas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableProjetos = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtProjeto = new javax.swing.JTextField();
        txtTarefa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel1HierarchyChanged(evt);
            }
        });
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(241, 172, 49));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText(" ");

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));
        jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("SRT-FreeLancers");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Gerir Projetos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(617, 617, 617)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(jLabel8)))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, -10, 1071, 150);

        jButton1.setBackground(new java.awt.Color(241, 172, 49));
        jButton1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 600, 200, 40);

        tableTarefas.setBackground(new java.awt.Color(204, 204, 204));
        tableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Drescrição"
            }
        ));
        tableTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTarefasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableTarefas);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(650, 200, 320, 270);

        tableProjetos.setBackground(new java.awt.Color(204, 204, 204));
        tableProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Nome", "Preço", "Total Horas", "Nome Cliente"
            }
        ));
        tableProjetos.setToolTipText("");
        tableProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProjetosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableProjetos);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(20, 200, 420, 270);

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("Remover Projeto");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(430, 200, 230, 40);

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("Adicionar Tarefa ao projeto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(430, 320, 230, 40);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Projeto:");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 510, 80, 27);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Tarefa:");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(650, 500, 60, 27);

        txtProjeto.setBackground(new java.awt.Color(204, 204, 204));
        txtProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjetoActionPerformed(evt);
            }
        });
        jPanel1.add(txtProjeto);
        txtProjeto.setBounds(90, 510, 250, 30);

        txtTarefa.setBackground(new java.awt.Color(204, 204, 204));
        txtTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarefaActionPerformed(evt);
            }
        });
        jPanel1.add(txtTarefa);
        txtTarefa.setBounds(720, 500, 250, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Lista de Projetos:");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 170, 170, 27);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Lista de Tarefas:");
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(590, 160, 170, 27);

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("Editar Projeto");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(440, 430, 210, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1HierarchyChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.parentFrame.trocaPainel(new Menu(this.parentFrame, this.utilizador.getUsername()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProjetosMouseClicked
        DefaultTableModel model = (DefaultTableModel) tableProjetos.getModel();
        int linha = tableProjetos.getSelectedRow();
        txtProjeto.setText(model.getValueAt(linha, 0).toString());
    }//GEN-LAST:event_tableProjetosMouseClicked

    private void tableTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTarefasMouseClicked
        DefaultTableModel model = (DefaultTableModel) tableTarefas.getModel();
        int linha = tableTarefas.getSelectedRow();
        txtTarefa.setText(model.getValueAt(linha, 0).toString());
    }//GEN-LAST:event_tableTarefasMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //input
        String nomeProj = txtProjeto.getText();
        //Variaveis
        boolean tarefasEmCurso = false;
        Set<Tarefas> guardaTarefas = null;
        Set<Projeto> guarda = new HashSet<>();
        
        for (Projeto proj : Repositorio.getInstance().getProjeto_tarefas().keySet()) {
            if (proj.getNome().equals(nomeProj)) {
                guardaTarefas = proj.getTarefaList();
                Iterator<Tarefas> iter = guardaTarefas.iterator();

                while (iter.hasNext()) {
                    Tarefas t = iter.next();
                    if (t.isIs_started()) {
                        tarefasEmCurso = true;
                        guarda.add(proj);
                    } else {
                        guarda.add(proj);
                    }

                }
            }
        }
        if (tarefasEmCurso) {
            int i = JOptionPane.showConfirmDialog(null,"Tarefas em curso! \nDeseja continuar?");
            if (i == JOptionPane.YES_OPTION) {
                for (Projeto proj : guarda) {
                Repositorio.getInstance().getProjeto_tarefas().remove(proj);
                RefreshTable();
                
            }
            JOptionPane.showMessageDialog(null, "Removido com Sucesso!");
            } else if (i == JOptionPane.NO_OPTION) {
                System.out.println("Clicou em Não");
            } else if (i == JOptionPane.CANCEL_OPTION) {
                System.out.println("Clicou em Cancel");
            }
        }if(!tarefasEmCurso){
            for (Projeto proj : guarda) {
                Repositorio.getInstance().getProjeto_tarefas().remove(proj);
                RefreshTable();
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Get linha selecionada
        DefaultTableModel model = (DefaultTableModel) tableProjetos.getModel();
        int linha = tableProjetos.getSelectedRow();
        //Variaveis
        String nome = (model.getValueAt(linha, 0).toString());
        Tarefas guarda = new Tarefas();
        boolean sucesso = false;

        //Adiciona uma Tarefa ao Projeto
        for (Projeto p : Repositorio.getInstance().getProjeto_tarefas().keySet()) {
            if (p.getUtil().contains(utilizador)) {
                guarda.setDescricao(this.txtTarefa.getText());
                if (p.getNome().equals(nome)) {
                    if(p.getTarefaList().contains(guarda)){
                        JOptionPane.showMessageDialog(null, "Tarefa já existe!");
                    }else{
                        if (verificaTarefa(guarda)) {
                            p.getTarefaList().add(guarda);
                            Repositorio.getInstance().getProjeto_tarefas().get(p).add(guarda);
                            sucesso = true;
                        }
                    
                    }
                }
            }
        }

        if (sucesso == true) {
            JOptionPane.showMessageDialog(null, "Tarefa Inserida com Sucesso!");

        } else {
            JOptionPane.showMessageDialog(null, "Informação inserida incorretamente!");
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjetoActionPerformed

    private void txtTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarefaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //Get Linha selecionada na tabela
        DefaultTableModel model = (DefaultTableModel) tableProjetos.getModel();
        int linha = tableProjetos.getSelectedRow();
        String nome = (model.getValueAt(linha, 0).toString());
        
        //Editar Projeto
        for (Projeto p : Repositorio.getInstance().getProjeto_tarefas().keySet()) {
            if (p.getUtil().contains(utilizador)) {
                if (p.getNome().equals(nome)) {
                    this.parentFrame.trocaPainel(new EditarProjeto(this.parentFrame, this.utilizador.getUsername(), p));
                }
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableProjetos;
    private javax.swing.JTable tableTarefas;
    private javax.swing.JTextField txtProjeto;
    private javax.swing.JTextField txtTarefa;
    // End of variables declaration//GEN-END:variables
}
